version: "3.5"
networks:
  fe:
  be:
services:
  mail:
    image: mailhog/mailhog
    networks:
      - be
      - fe
    ports:
      - "${SMTP_PORT:-1025}:1025"
      - "${MH_ADMIN_PORT:-8025}:8025"
  rabbitmq:
    image: obliquo/clustered-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_ERLANG_COOKIE=rabbitmq
    networks:
      - be
    ports:
      - 15672
  consul:
    hostname: consul
    image: consul
    ports:
      - "${CONSUL_PORT:-8500}:8500"
    networks:
      - be
  haproxy:
    hostname: proxy
    image: obliquo/rabbitmq-lb
    ports:
      - "${HPXY_PORT:-9000}:9000"
      - "${RMQ_PORT:-5672}:5672"
    networks:
      - fe
      - be
  influxdb:
    hostname: influxdb
    image: influxdb:1.3-alpine
    networks:
      - be
  grafana:
    hostname: grafana
    image: grafana/grafana
    environment:
        - "GF_SECURITY_ADMIN_PASSWORD=admin"
    networks:
        - be
        - fe
    ports:
        - "${GRAFANA_PORT:-3000}:3000"
  telegraf:
    hostname: telegraf
    image: telegraf
    volumes:
      - ./infra/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - be
      - fe
    ports:
      - "${STATSD_PORT:-8125}:8125/udp"
  users:
    image: obliquo/users-double
    networks:
      - be
      - fe
    ports:
      - "${USERS_PORT:-9999}:9999"
